version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    command: ["ollama", "pull", "llama3.2"]

  app:
    build: .
    container_name: fastapi_app
    depends_on:
      - ollama
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]

volumes:
  ollama: